services:
  - type: web
    name: auth-system
    env: node
    buildCommand: npm install && npm run build:prod
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: TWO_FACTOR_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false 